using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Net;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Security.Principal;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows.Forms;
using Microsoft.Win32;
using Microsoft.Win32.SafeHandles;
using System.Xml;

namespace UupDumpFetcher
{
    // =========================================================================
    //  Main form
    // =========================================================================
    class MainForm : Form
    {
        // Pulled from the compiled assembly (AssemblyVersion.generated.cs,
        // regenerated by build.cmd every compile) rather than a fixed string
        // here, so the title bar tracks the real build - see CLAUDE.md's
        // "Assembly version auto-increments every build" section.
        static readonly string AppVersion =
            Assembly.GetExecutingAssembly().GetName().Version.ToString();

        // UI controls
        RichTextBox _logBox;
        FlatProgressBar _dlBar, _spinBar;
        Label       _lblProgress;   // "45.2 / 312.0 MB  –  12.3 MB/s"
        TextBox     _tbBuild, _tbUploadDest, _tbUserAgent, _tbDownloadDir;
        ComboBox    _cmbArch;
        CheckBox    _cbMonitor, _cbRunProcessor, _cbCleanup, _cbSkipUpload;
        CheckBox    _cb26H2, _cb26H1, _cb23H2;
        Button      _btnStart, _btnStop;
        TabControl  _tabs;
        TabPage     _tabFetch, _tabSettings;
        Panel       _tabRowFill;   // covers the native light strip right of the last tab
        Panel       _tabFrameTop, _tabFrameBottom;  // cover TabAppearance.Normal's light notebook-frame border
        Panel       _tabFrameLeft, _tabFrameRight;  // same frame border, left/right edges
        Panel       _tabGroupTop;   // FlatButtons' own button-group outline, top edge
        Panel       _tabInterGapFill;  // gap FlatButtons leaves between adjacent tab buttons
        // _cmbArch's own FlatStyle.Flat border/dropdown-button chrome always
        // renders a fixed light gray regardless of theme (same native-quirk
        // class as TextBox's FixedSingle border) - these cover it, dark mode
        // only (see ApplyTheme). _archButtonFace also owner-paints its own
        // dropdown arrow glyph, since it fully covers the native one.
        Panel       _archBorderLeft, _archBorderTop, _archBorderBottom, _archButtonFace;

        // Worker state
        bool             _busy;
        Thread           _worker;
        ManualResetEvent _stopEvent = new ManualResetEvent(false);

        // Progress values written by worker thread, read by UI timer.
        // Volatile long is not atomic on x86 but close enough for display.
        volatile int  _progPct;
        long          _progDone;   // Interlocked
        long          _progTotal;  // Interlocked
        double        _progSpeed;  // written under _logLock

        // Thread-safe log queue
        readonly Queue<string> _logQueue  = new Queue<string>();
        readonly object        _logLock   = new object();
        System.Windows.Forms.Timer _logTimer;

        public MainForm()
        {
            AppConfig.Load();
            Paths.SetDownloadDir(AppConfig.DownloadDir);
            Theme.IsDark = DetectDarkMode();

            SuspendLayout();
            Text          = "UUP Dump Fetcher v" + AppVersion;
            MinimumSize   = new Size(980, 660);
            Size          = new Size(1100, 720);
            StartPosition = FormStartPosition.CenterScreen;
            BackColor     = Theme.Bg;
            Font          = Ctrl.SegoUI();
            try
            {
                Icon = Icon.ExtractAssociatedIcon(
                    Process.GetCurrentProcess().MainModule.FileName);
            }
            catch { }

            BuildUI();
            // Apply the current theme to all entry/combo fields now that
            // controls exist (covers users whose OS theme differs from the
            // default).
            ApplyTheme();
            ResumeLayout(false);

            // Log messages are queued by the worker thread; the UI timer
            // drains the queue in batches so the message pump stays free.
            Logger.MessageLogged += delegate(string msg) { QueueLog(msg); };

            // 100 ms UI refresh timer: flushes log queue + refreshes progress.
            _logTimer          = new System.Windows.Forms.Timer();
            _logTimer.Interval = 100;
            _logTimer.Tick    += delegate(object s, EventArgs e) { OnUiTick(); };
            _logTimer.Start();
        }

        static bool DetectDarkMode()
        {
            try
            {
                RegistryKey key = Registry.CurrentUser.OpenSubKey(
                    @"Software\Microsoft\Windows\CurrentVersion\Themes\Personalize");
                if (key == null) return true;
                object v = key.GetValue("AppsUseLightTheme");
                key.Close();
                return v == null || (int)v == 0;
            }
            catch { return true; }
        }

        protected override void OnHandleCreated(EventArgs e)
        {
            base.OnHandleCreated(e);
            QueueLog("Ready.  Downloads: " + Paths.DownloadDir);
            if (string.IsNullOrEmpty(AppConfig.UploadDest) && !AppConfig.SkipUpload)
                QueueLog("WARN: No upload destination set – configure it in the Settings tab.");
            if (AppConfig.MonitorMode)
            {
                QueueLog("Monitor mode enabled in config – auto-starting fetch...");
                BeginInvoke(new Action(delegate() { OnStart(); }));
            }
        }

        // ── Build UI ──────────────────────────────────────────────────────────
        void BuildUI()
        {
            // Top bar
            Panel topBar     = new Panel();
            topBar.Dock      = DockStyle.Top;
            topBar.Height    = 48;
            topBar.BackColor = Theme.Surface;

            Label lblTitle   = Ctrl.MakeLabel("⬇  UUP Dump Fetcher", false, 14);
            lblTitle.Font    = Ctrl.SegoUI(14, FontStyle.Bold);
            lblTitle.Location = new Point(16, 10);

            Button btnTheme   = new Button();
            btnTheme.Text     = Theme.IsDark ? "\u2600" : "\uD83C\uDF19";
            btnTheme.Width    = 36; btnTheme.Height = 28;
            btnTheme.FlatStyle = FlatStyle.Flat;
            btnTheme.BackColor = Theme.Surface; btnTheme.ForeColor = Theme.Fg;
            btnTheme.Font     = Ctrl.SegoUI(11);
            btnTheme.Anchor   = AnchorStyles.Right | AnchorStyles.Top;
            btnTheme.FlatAppearance.BorderSize = 0;
            btnTheme.Click   += delegate(object s, EventArgs e)
            {
                Theme.IsDark  = !Theme.IsDark;
                btnTheme.Text = Theme.IsDark ? "\u2600" : "\uD83C\uDF19";
                ApplyTheme();
            };
            topBar.Resize    += delegate(object s, EventArgs e)
            {
                btnTheme.Location = new Point(
                    topBar.Width - btnTheme.Width - 12,
                    (topBar.Height - btnTheme.Height) / 2);
            };
            topBar.Controls.Add(lblTitle);
            topBar.Controls.Add(btnTheme);

            Panel sep = new Panel();
            sep.Dock = DockStyle.Top; sep.Height = 1; sep.BackColor = Theme.Border;

            _tabs         = new TabControl();
            _tabs.Dock    = DockStyle.Fill;
            // Padding only pads the measured ItemSize below (extra breathing
            // room around each tab's text) - it does NOT affect centering,
            // since DrawTab always centers text within GetTabRect(index),
            // the tab's own real rectangle, regardless of this value.
            _tabs.Padding = new Point(18, 7);
            _tabs.Font    = Ctrl.SegoUI();
            // Native TabControl always paints its tab strip via visual
            // styles - light/white regardless of BackColor/ForeColor.
            // OwnerDrawFixed + DrawTab paints each real tab's own rectangle
            // to match Theme. FlatButtons vs Normal: see CLAUDE.md's "Visual
            // overhaul" section for the full live-tested history - Normal
            // draws each tab as a bordered notebook-tab shape (a persistent
            // light outline around every tab that OwnerDraw doesn't reach,
            // since it only paints inside e.Bounds, not the native border
            // decoration around it) and its own light frame border around
            // the whole page area; FlatButtons drops both, at the cost of a
            // light strip in the tab row that needed the _tabRowFill/
            // _tabFrame* overlay panels below regardless of which Appearance
            // is used - now that those exist, FlatButtons is the better
            // choice since it needs no fighting with the native tab-shape
            // border at all.
            _tabs.Appearance = TabAppearance.FlatButtons;
            _tabs.DrawMode   = TabDrawMode.OwnerDrawFixed;
            _tabs.DrawItem  += DrawTab;

            // Fixed, measured width for every tab - SizeMode.Normal (the
            // default) auto-sizes each tab to its own text, so "Settings"
            // (8 chars) renders visibly wider than "Fetch" (5 chars).
            // Measured from the actual longer label rather than a
            // hand-picked constant (DrawTab already centers text within
            // whatever bounds the control gives each tab regardless of
            // SizeMode, so this only changes sizing, not painting).
            Size fetchSz    = TextRenderer.MeasureText("Fetch", _tabs.Font);
            Size settingsSz = TextRenderer.MeasureText("Settings", _tabs.Font);
            int tabTextW = Math.Max(fetchSz.Width, settingsSz.Width);
            _tabs.SizeMode = TabSizeMode.Fixed;
            _tabs.ItemSize = new Size(tabTextW + _tabs.Padding.X * 2, fetchSz.Height + _tabs.Padding.Y * 2);

            _tabFetch    = new TabPage("Fetch");
            _tabSettings = new TabPage("Settings");
            _tabs.TabPages.Add(_tabFetch);
            _tabs.TabPages.Add(_tabSettings);


            // Status bar at the bottom - use TableLayoutPanel to avoid
            // z-order/Dock conflicts that hid the progress bar previously.
            Panel statusBar     = new Panel();
            statusBar.Dock      = DockStyle.Bottom;
            statusBar.Height    = 42;
            statusBar.BackColor = Theme.Surface;

            // 3-column layout: label (55%) | progress bar (45%) | Stop (fixed)
            // Spinner removed - Stop button being enabled is sufficient running feedback.
            TableLayoutPanel sbLayout = new TableLayoutPanel();
            sbLayout.Dock        = DockStyle.Fill;
            sbLayout.ColumnCount = 4;
            sbLayout.RowCount    = 1;
            sbLayout.BackColor   = Color.Transparent;
            sbLayout.Padding     = new Padding(8, 0, 8, 0);
            sbLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 55));
            sbLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 45));
            sbLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 60));
            sbLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 98));
            sbLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100));

            _lblProgress           = new Label();
            _lblProgress.Dock      = DockStyle.Fill;
            _lblProgress.Font      = Ctrl.SegoUI(8.25f);
            _lblProgress.ForeColor = Theme.FgDim;
            _lblProgress.BackColor = Color.Transparent;
            _lblProgress.TextAlign = ContentAlignment.MiddleLeft;
            _lblProgress.Text      = "Idle";

            _dlBar        = new FlatProgressBar();
            _dlBar.Dock   = DockStyle.Fill;
            _dlBar.Margin = new Padding(0, 13, 8, 13);

            _spinBar         = new FlatProgressBar();
            _spinBar.Dock    = DockStyle.Fill;
            _spinBar.Marquee = true;
            _spinBar.Margin  = new Padding(0, 14, 4, 14);
            _spinBar.Visible = false;  // shown by SetBusy(true)

            _btnStop         = Ctrl.DangerButton("■  Stop");
            _btnStop.Dock    = DockStyle.Fill;
            _btnStop.Margin  = new Padding(0, 6, 0, 6);
            _btnStop.Enabled = false;
            _btnStop.Click  += delegate(object s, EventArgs e) { OnStop(); };

            sbLayout.Controls.Add(_lblProgress, 0, 0);
            sbLayout.Controls.Add(_dlBar,       1, 0);
            sbLayout.Controls.Add(_spinBar,     2, 0);
            sbLayout.Controls.Add(_btnStop,     3, 0);
            statusBar.Controls.Add(sbLayout);

            Controls.Add(_tabs);
            Controls.Add(sep);
            Controls.Add(topBar);
            Controls.Add(statusBar);

            // The strip to the right of the last real tab, within the same
            // row, is native-painted by the TabControl regardless of
            // BackColor and regardless of NativeMethods.DisableVisualStyles
            // (tried both, pixel-checked a real screenshot each time - still
            // R=G=B=240 either way). A control added directly to
            // _tabs.Controls (rather than to one of its TabPages) never
            // renders at all - verified live with an oversized bright-red
            // debug rectangle that simply never appeared no matter what.
            // Fix: a plain Panel added as a *sibling* of _tabs (a child of
            // this Form, added after _tabs so it paints on top), positioned
            // in the Form's own coordinate space via _tabs.Location + the
            // real tab rect - ordinary sibling z-ordering works completely
            // normally here, unlike TabControl's own child handling.
            _tabRowFill = new Panel();
            _tabRowFill.BackColor = Theme.Bg;
            Controls.Add(_tabRowFill);
            _tabRowFill.BringToFront();

            // TabAppearance.Normal also draws its own light "notebook frame"
            // border around the whole page area - a thin (2px) full-width
            // line immediately below the tab row, and another one near the
            // bottom of the TabControl's own client area. Missed on the
            // first verification pass because that only spot-checked pixels
            // every 20px vertically, which happened to step over both of
            // these - caught only by a full row-by-row scan of a real
            // screenshot (a general lesson: a coarse pixel-check grid can
            // walk right past a thin border the same way eyeballing can).
            _tabFrameTop = new Panel();
            _tabFrameTop.BackColor = Theme.Bg;
            Controls.Add(_tabFrameTop);
            _tabFrameTop.BringToFront();

            _tabFrameBottom = new Panel();
            _tabFrameBottom.BackColor = Theme.Bg;
            Controls.Add(_tabFrameBottom);
            _tabFrameBottom.BringToFront();

            // Same notebook-frame border, left/right edges this time - found
            // by extending the verification scanner to check columns as well
            // as rows after the user reported these specifically (the row
            // scan alone had no way to reveal a vertical line).
            _tabFrameLeft = new Panel();
            _tabFrameLeft.BackColor = Theme.Bg;
            Controls.Add(_tabFrameLeft);
            _tabFrameLeft.BringToFront();

            _tabFrameRight = new Panel();
            _tabFrameRight.BackColor = Theme.Bg;
            Controls.Add(_tabFrameRight);
            _tabFrameRight.BringToFront();

            // FlatButtons' button-group outline's top edge - only actually
            // visible over an *unselected* tab (the selected tab's own
            // DrawTab fill happens to already cover it there), found by
            // re-scanning yet again after the left/right/bottom fixes above
            // and seeing a new short span appear specifically over
            // "Settings", not "Fetch".
            _tabGroupTop = new Panel();
            _tabGroupTop.BackColor = Theme.Bg;
            Controls.Add(_tabGroupTop);
            _tabGroupTop.BringToFront();

            // FlatButtons also leaves a visible gap *between* adjacent tab
            // buttons (found via a direct per-pixel region scan, not the
            // find_light.exe row/column heuristic - that tool's column pass
            // missed this because the same column also crosses the unrelated
            // TextBox border further down the form, which diluted its
            // density-over-full-column-span check below threshold even
            // though the two are separate defects. Lesson: a "wide span,
            // high density" heuristic can hide a real short defect if an
            // unrelated defect elsewhere in the same column/row lowers the
            // overall density - when a heuristic scan comes back clean but
            // something still looks visually wrong, re-check with a raw,
            // unfiltered per-pixel dump of just the suspect region instead of
            // trusting the heuristic's negative result.
            _tabInterGapFill = new Panel();
            _tabInterGapFill.BackColor = Theme.Bg;
            Controls.Add(_tabInterGapFill);
            _tabInterGapFill.BringToFront();

            Action layoutTabRowFill = delegate()
            {
                if (_tabs.TabCount == 0) return;
                Rectangle lastTabRect = _tabs.GetTabRect(_tabs.TabCount - 1);
                // Cover from _tabs.Top directly (not _tabs.Top + lastTabRect.Top)
                // down through lastTabRect.Bottom - GetTabRect's own small top
                // offset (a couple px of padding above the tab text) otherwise
                // leaves a thin sliver of the native light strip uncovered at
                // the very top of the row, found by pixel-checking a real
                // screenshot row-by-row rather than assuming one check at the
                // rect's own bounds was enough.
                // A few px earlier than lastTabRect.Right itself - same kind
                // of small boundary-offset margin as _tabFrameTop's Y below,
                // found the same way (a real screenshot still showed a thin
                // sliver at x=198-199 with this starting exactly at
                // lastTabRect.Right and no margin).
                _tabRowFill.Location = new Point(_tabs.Left + lastTabRect.Right - 3, _tabs.Top);
                _tabRowFill.Size = new Size(Math.Max(0, _tabs.Width - lastTabRect.Right + 3), lastTabRect.Bottom);

                // The gap FlatButtons leaves *between* adjacent tab buttons -
                // only covers one gap (assumes exactly 2 tabs, Fetch and
                // Settings, which is all this app has; extend to loop over
                // every adjacent pair if a third tab is ever added).
                if (_tabs.TabCount >= 2)
                {
                    Rectangle firstTabRect = _tabs.GetTabRect(0);
                    Rectangle secondTabRect = _tabs.GetTabRect(1);
                    _tabInterGapFill.Location = new Point(
                        _tabs.Left + firstTabRect.Right - 2, _tabs.Top);
                    _tabInterGapFill.Size = new Size(
                        Math.Max(0, secondTabRect.Left - firstTabRect.Right + 4), lastTabRect.Bottom);
                }

                // Starts 3px above the tab row's own reported bottom edge -
                // confirmed live (a same-process GetTabRect+screenshot cross-
                // check, see DrawTab's comment) that a real native page-frame
                // highlight line sits right at this boundary REGARDLESS of
                // owner-draw or tab selection (present under both Fetch and
                // Settings alike, at the identical row, well before this
                // panel even existed) - not a gap left by owner-draw
                // painting short of GetTabRect's bottom, which was this
                // comment's earlier (wrong) theory: e.Bounds only insets
                // ~2px from GetTabRect (the ordinary owner-draw content
                // margin), nowhere near enough to explain a 7px-tall native
                // line. Reverted back to -3 after moving it to 0 (matching
                // the wrong theory) reintroduced that native line as a real
                // visible defect. Trade-off, confirmed acceptable: this
                // means the panel also covers the last ~2px of the tab's own
                // accent underline (drawn at bounds.Bottom-1/-2, the same
                // rows the native line occupies) - hiding a real, previously-
                // fixed defect matters more than showing the underline.
                _tabFrameTop.Location = new Point(_tabs.Left, _tabs.Top + lastTabRect.Bottom - 3);
                _tabFrameTop.Size = new Size(_tabs.Width, 7);

                // Sits well above where any tab's own text starts (Padding.Y
                // = 7, so labels begin ~7px down) - safe across the full
                // width including over "Fetch", where it just harmlessly
                // overlaps that tab's own already-dark fill.
                _tabGroupTop.Location = new Point(_tabs.Left, _tabs.Top);
                _tabGroupTop.Size = new Size(_tabs.Width, 4);

                _tabFrameBottom.Location = new Point(_tabs.Left, _tabs.Bottom - 6);
                _tabFrameBottom.Size = new Size(_tabs.Width, 6);

                // Left/right edges of the same frame - found at ~8-11px and
                // ~11px in from the control's own left/right edges
                // respectively (a real screenshot scan, not assumed); 14px
                // covers both with margin. Spans the FULL _tabs.Height,
                // including the tab-row itself - FlatButtons' button-group
                // outline (see _tabFrameTop's own comment) runs along the
                // left/right edges of the tab row too, not just below it.
                // Safe to cover that high up despite real tab labels sitting
                // in the same row: _tabs.Padding insets every tab's own text
                // 18px from that tab's edge, and the first tab starts at
                // x~0-4, so a 14px-wide strip from the control's own left
                // edge never reaches an actual glyph.
                _tabFrameLeft.Location = new Point(_tabs.Left, _tabs.Top);
                _tabFrameLeft.Size = new Size(4, _tabs.Height);

                _tabFrameRight.Location = new Point(_tabs.Right - 4, _tabs.Top);
                _tabFrameRight.Size = new Size(4, _tabs.Height);
            };
            layoutTabRowFill();
            _tabs.Resize += delegate(object s, EventArgs e) { layoutTabRowFill(); };

            BuildFetchTab();
            BuildSettingsTab();
        }

        // ── Fetch tab ─────────────────────────────────────────────────────────
        void BuildFetchTab()
        {
            _tabFetch.BackColor = Theme.Bg;

            // Left panel (controls)
            Panel left  = new Panel();
            left.Dock   = DockStyle.Left;
            left.Width  = 310;
            left.Padding = new Padding(18);
            left.BackColor = Color.Transparent;

            // Right panel (log)
            Panel right = new Panel();
            right.Dock  = DockStyle.Fill;
            right.Padding = new Padding(0, 18, 18, 0);
            right.BackColor = Color.Transparent;

            _tabFetch.Controls.Add(right);
            _tabFetch.Controls.Add(left);

            // --- Left controls ---
            int y = 18;
            Action<Control> Add = null;
            Add = delegate(Control c)
            {
                c.Left  = 18; c.Top = y; c.Width = 268;
                left.Controls.Add(c);
                y += c.Height + 6;
            };
            Action Sep = delegate()
            {
                Panel p = new Panel();
                p.Height = 1; p.BackColor = Theme.Border;
                Add(p); y += 4;
            };
            Action<string> Sec = delegate(string title)
            {
                Label l = Ctrl.MakeLabel(title.ToUpper(), true, 8f);
                l.Font = Ctrl.SegoUI(8f, FontStyle.Bold);
                Add(l); y += 2;
            };

            Sec("Fetch Options");

            Add(Ctrl.MakeLabel("Specific build  (e.g. 26100.7092)", true));

            _tbBuild = Ctrl.MakeEntry();
            _tbBuild.Height = 24;
            Add(Ctrl.Bordered(_tbBuild));

            y += 4;
            Label lblArch = Ctrl.MakeLabel("Architecture  (manual build only)", true);
            Add(lblArch);

            _cmbArch = new ComboBox();
            _cmbArch.DropDownStyle = ComboBoxStyle.DropDownList;
            _cmbArch.Height        = 24;
            _cmbArch.Font          = Ctrl.SegoUI();
            _cmbArch.BackColor     = Theme.IsDark ? Theme.EntryBg : SystemColors.Window;
            _cmbArch.ForeColor     = Theme.IsDark ? Theme.EntryFg : SystemColors.WindowText;
            _cmbArch.FlatStyle     = Theme.IsDark ? FlatStyle.Flat : FlatStyle.Standard;
            // BackColor/ForeColor only theme the closed display portion - the
            // dropdown list popup (what actually shows "amd64 + arm64" /
            // "amd64 only" / "arm64 only" when clicked) is a separate native
            // listbox that Windows always renders with its own default
            // white/black colors regardless, the same class of "native
            // control ignores BackColor for one specific part of itself"
            // problem TabControl's header/frame had. OwnerDrawFixed +
            // DrawItem (DrawComboItem) is the fix, same technique as DrawTab.
            _cmbArch.DrawMode = DrawMode.OwnerDrawFixed;
            _cmbArch.DrawItem += DrawComboItem;
            _cmbArch.Items.Add("amd64 + arm64");
            _cmbArch.Items.Add("amd64 only");
            _cmbArch.Items.Add("arm64 only");
            _cmbArch.SelectedIndex = 0;
            _cmbArch.Enabled       = false;   // enabled only when build is specified
            Add(_cmbArch);

            // Cover _cmbArch's own native FlatStyle.Flat chrome - confirmed
            // live via pixel-check that it renders a fixed light gray
            // (240,240,240) border (~3px on left/top/bottom) AND the entire
            // dropdown-button face (the rightmost ~20px, arrow glyph
            // included) regardless of BackColor/ForeColor, the same native-
            // quirk class as TextBox's FixedSingle border. DrawComboItem
            // (DrawMode.OwnerDrawFixed) only paints the closed box's own
            // text area (e.Index == -1) and each open-list row - it never
            // touches this surrounding chrome. Sized from _cmbArch's own
            // real Bounds/PreferredHeight (not the 24 assigned above, which
            // - like TextBox.Height - is silently overridden by Windows to
            // the font's natural combo height) so this stays correct if the
            // font ever changes; the 3px/20px thicknesses themselves are
            // empirical (measured via a live pixel-scan across the real
            // border and button-face extent), not computable from any
            // ComboBox property.
            _archBorderLeft = new Panel();
            _archBorderTop = new Panel();
            _archBorderBottom = new Panel();
            _archButtonFace = new Panel();
            left.Controls.Add(_archBorderLeft);
            left.Controls.Add(_archBorderTop);
            left.Controls.Add(_archBorderBottom);
            left.Controls.Add(_archButtonFace);
            int archH = _cmbArch.PreferredHeight;
            _archBorderLeft.Bounds = new Rectangle(_cmbArch.Left, _cmbArch.Top, 3, archH);
            _archBorderTop.Bounds = new Rectangle(_cmbArch.Left, _cmbArch.Top, _cmbArch.Width, 3);
            _archBorderBottom.Bounds = new Rectangle(_cmbArch.Left, _cmbArch.Top + archH - 3, _cmbArch.Width, 3);
            _archButtonFace.Bounds = new Rectangle(_cmbArch.Left + _cmbArch.Width - 20, _cmbArch.Top, 20, archH);
            _archButtonFace.Paint += delegate(object s, PaintEventArgs e)
            {
                using (SolidBrush b = new SolidBrush(Theme.FgDim))
                {
                    int cx = _archButtonFace.Width / 2, cy = _archButtonFace.Height / 2;
                    Point[] tri = new Point[] {
                        new Point(cx - 4, cy - 2), new Point(cx + 4, cy - 2), new Point(cx, cy + 3)
                    };
                    e.Graphics.FillPolygon(b, tri);
                }
            };
            _archBorderLeft.BringToFront();
            _archBorderTop.BringToFront();
            _archBorderBottom.BringToFront();
            _archButtonFace.BringToFront();

            // Enable/disable arch selector based on whether a build is typed
            _tbBuild.TextChanged += delegate(object s, EventArgs e)
            {
                _cmbArch.Enabled = _tbBuild.Text.Trim().Length > 0;
                if (!_cmbArch.Enabled) _cmbArch.SelectedIndex = 0;
            };

            y += 10;
            _btnStart = Ctrl.AccentButton("▶  Start Fetching");
            _btnStart.Click += delegate(object s, EventArgs e) { OnStart(); };
            Add(_btnStart);

            y += 12; Sep(); y += 4;
            Sec("Download State");

            Button btnViewState = Ctrl.NormalButton("View Downloaded Builds");
            btnViewState.Click += delegate(object s, EventArgs e) { ShowState(); };
            Add(btnViewState);

            y += 2;
            Button btnClearState = Ctrl.DangerButton("Clear State File");
            btnClearState.Click += delegate(object s, EventArgs e) { ClearState(); };
            Add(btnClearState);

            y += 12; Sep(); y += 4;
            Sec("Log");
            Button btnClearLog = Ctrl.NormalButton("Clear Log");
            btnClearLog.Click += delegate(object s, EventArgs e) { ClearLog(); };
            Add(btnClearLog);

            // --- Right: log box ---
            Label lblOut = Ctrl.MakeLabel("Output", false, 11f);
            lblOut.Font   = Ctrl.SegoUI(11f, FontStyle.Bold);
            lblOut.Dock   = DockStyle.Top;
            lblOut.Height = 26;

            Panel logWrap = new Panel();
            logWrap.Dock      = DockStyle.Fill;
            logWrap.BackColor = Theme.Border;

            _logBox             = new RichTextBox();
            _logBox.Dock        = DockStyle.Fill;
            _logBox.ReadOnly    = true;
            _logBox.BackColor   = Theme.LogBg;
            _logBox.ForeColor   = Theme.LogFg;
            _logBox.Font        = new Font("Consolas", 8.25f);
            _logBox.BorderStyle = BorderStyle.None;
            _logBox.WordWrap    = true;
            _logBox.ScrollBars  = RichTextBoxScrollBars.Vertical;
            _logBox.DetectUrls  = true;
            _logBox.LinkClicked += delegate(object s2, LinkClickedEventArgs e2)
            { try { Process.Start(e2.LinkText); } catch { } };
            // Accessing .Handle forces the native control to be created now,
            // so this is safe here rather than needing an OnHandleCreated hook.
            NativeMethods.EnableDarkScrollBar(_logBox.Handle);

            logWrap.Controls.Add(_logBox);
            right.Controls.Add(logWrap);
            right.Controls.Add(lblOut);
        }

        // ── Settings tab ──────────────────────────────────────────────────────
        void BuildSettingsTab()
        {
            _tabSettings.BackColor = Theme.Bg;

            TableLayoutPanel tl = new TableLayoutPanel();
            tl.Dock        = DockStyle.Fill;
            tl.ColumnCount = 2;
            tl.Padding     = new Padding(28);
            tl.BackColor   = Color.Transparent;
            tl.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
            tl.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));

            // Download destination (editable, with browse) - FIRST
            Panel ddRow = new Panel();
            ddRow.Dock = DockStyle.Fill; ddRow.Height = 26;
            _tbDownloadDir = Ctrl.MakeEntry();
            _tbDownloadDir.Text   = Paths.DownloadDir;
            _tbDownloadDir.Height = 24;
            Panel tbDownloadDirWrap = Ctrl.Bordered(_tbDownloadDir);
            tbDownloadDirWrap.Dock = DockStyle.Fill;

            Button btnBrowseDl = new Button();
            btnBrowseDl.Text      = "..."; btnBrowseDl.Width = 34;
            btnBrowseDl.FlatStyle = FlatStyle.Flat;
            btnBrowseDl.BackColor = Theme.Border; btnBrowseDl.ForeColor = Theme.Fg;
            btnBrowseDl.Cursor    = Cursors.Hand; btnBrowseDl.Dock = DockStyle.Right;
            btnBrowseDl.FlatAppearance.BorderSize = 0;
            btnBrowseDl.Click += delegate(object s, EventArgs e)
            {
                FolderBrowserDialog dlg = new FolderBrowserDialog();
                dlg.Description = "Select download / working directory";
                if (dlg.ShowDialog(this) == DialogResult.OK)
                    _tbDownloadDir.Text = dlg.SelectedPath;
            };
            ddRow.Controls.Add(tbDownloadDirWrap);
            ddRow.Controls.Add(btnBrowseDl);
            AddSettingRow(tl, "Download destination", ddRow, 0);

            // Upload destination - SECOND
            Panel destRow = new Panel();
            destRow.Dock = DockStyle.Fill; destRow.Height = 26;
            _tbUploadDest = Ctrl.MakeEntry();
            _tbUploadDest.Text   = AppConfig.UploadDest;
            _tbUploadDest.Height = 24;
            Panel tbUploadDestWrap = Ctrl.Bordered(_tbUploadDest);
            tbUploadDestWrap.Dock = DockStyle.Fill;

            Button btnBrowse = new Button();
            btnBrowse.Text      = "..."; btnBrowse.Width = 34;
            btnBrowse.FlatStyle = FlatStyle.Flat;
            btnBrowse.BackColor = Theme.Border; btnBrowse.ForeColor = Theme.Fg;
            btnBrowse.Cursor    = Cursors.Hand; btnBrowse.Dock = DockStyle.Right;
            btnBrowse.FlatAppearance.BorderSize = 0;
            btnBrowse.Click += delegate(object s, EventArgs e)
            {
                FolderBrowserDialog dlg = new FolderBrowserDialog();
                dlg.Description = "Select upload destination folder";
                if (dlg.ShowDialog(this) == DialogResult.OK)
                    _tbUploadDest.Text = dlg.SelectedPath;
            };
            destRow.Controls.Add(tbUploadDestWrap);
            destRow.Controls.Add(btnBrowse);

            AddSettingRow(tl, "Upload destination\n(e.g. Z:\\ or \\\\server\\share)", destRow, 1);

            _tbUserAgent      = Ctrl.MakeEntry();
            _tbUserAgent.Text = AppConfig.UserAgent;
            _tbUserAgent.Height = 24;
            AddSettingRow(tl, "Browser user-agent", Ctrl.Bordered(_tbUserAgent), 2);

            Panel sep1 = new Panel();
            sep1.Height = 1; sep1.BackColor = Theme.Border;
            sep1.Margin = new Padding(0, 10, 0, 10);
            tl.SetColumnSpan(sep1, 2); tl.Controls.Add(sep1, 0, 3);

            _cbRunProcessor = Ctrl.MakeCheck("Process update to ESD");
            _cbRunProcessor.Checked = AppConfig.RunProcessor;

            _cbCleanup = Ctrl.MakeCheck("Cleanup working dir after upload");
            _cbCleanup.Checked = AppConfig.CleanupAfterUpload;
            _cbSkipUpload = Ctrl.MakeCheck("Skip upload");
            _cbSkipUpload.Checked = AppConfig.SkipUpload && !AppConfig.CleanupAfterUpload;

            // Skip upload is meaningless when Cleanup is on — they would
            // delete the locally processed files without uploading them first.
            _cbSkipUpload.Enabled = !_cbCleanup.Checked;
            _cbCleanup.CheckedChanged += delegate(object s, EventArgs e)
            {
                _cbSkipUpload.Enabled = !_cbCleanup.Checked;
                if (_cbCleanup.Checked) _cbSkipUpload.Checked = false;
            };

            _cbMonitor = Ctrl.MakeCheck("Monitor mode  (auto-scan every 5 min)");
            _cbMonitor.Checked = AppConfig.MonitorMode;

            FlowLayoutPanel checks = new FlowLayoutPanel();
            checks.FlowDirection = FlowDirection.TopDown;
            checks.WrapContents  = false; checks.AutoSize = true;
            checks.BackColor     = Color.Transparent;
            checks.Controls.Add(_cbMonitor);
            checks.Controls.Add(_cbRunProcessor);
            checks.Controls.Add(_cbCleanup);
            checks.Controls.Add(_cbSkipUpload);
            tl.SetColumnSpan(checks, 2); tl.Controls.Add(checks, 0, 4);

            Panel sep2 = new Panel();
            sep2.Height = 1; sep2.BackColor = Theme.Border;
            sep2.Margin = new Padding(0, 10, 0, 10);
            tl.SetColumnSpan(sep2, 2); tl.Controls.Add(sep2, 0, 5);

            // Windows 11 version selection
            tl.Controls.Add(Ctrl.MakeLabel("Windows 11 versions to scan", false), 0, 6);

            _cb26H2 = Ctrl.MakeCheck("Windows 11 26H2");
            _cb26H2.Checked = AppConfig.Branch26H2;
            _cb26H1 = Ctrl.MakeCheck("Windows 11 26H1");
            _cb26H1.Checked = AppConfig.Branch26H1;
            _cb23H2 = Ctrl.MakeCheck("Windows 11 23H2");
            _cb23H2.Checked = AppConfig.Branch23H2;

            FlowLayoutPanel verChecks = new FlowLayoutPanel();
            verChecks.FlowDirection = FlowDirection.TopDown;
            verChecks.WrapContents  = false; verChecks.AutoSize = true;
            verChecks.BackColor     = Color.Transparent;
            verChecks.Controls.Add(_cb26H2);
            verChecks.Controls.Add(_cb26H1);
            verChecks.Controls.Add(_cb23H2);
            tl.Controls.Add(verChecks, 1, 6);

            Panel sep3 = new Panel();
            sep3.Height = 1; sep3.BackColor = Theme.Border;
            sep3.Margin = new Padding(0, 10, 0, 10);
            tl.SetColumnSpan(sep3, 2); tl.Controls.Add(sep3, 0, 7);

            tl.Controls.Add(Ctrl.MakeLabel("Config file",  true), 0, 8);
            tl.Controls.Add(Ctrl.MakeLabel(Paths.ConfigFile,  true), 1, 8);
            tl.Controls.Add(Ctrl.MakeLabel("State file",   true), 0, 9);
            tl.Controls.Add(Ctrl.MakeLabel(Paths.StateFile,   true), 1, 9);
            tl.Controls.Add(Ctrl.MakeLabel("Data dir",     true), 0, 11);
            tl.Controls.Add(Ctrl.MakeLabel(Paths.LogFile, true), 1, 10);
            tl.Controls.Add(Ctrl.MakeLabel("Log file",     true), 0, 10);
            tl.Controls.Add(Ctrl.MakeLabel(Paths.DataDir, true), 1, 11);

            Button btnFolder = Ctrl.NormalButton("Open download folder");
            btnFolder.Dock   = DockStyle.Fill;
            btnFolder.Margin = new Padding(18, 6, 0, 2);
            btnFolder.Click += delegate(object s, EventArgs e)
            { try { Process.Start("explorer.exe", Paths.DownloadDir); } catch { } };
            tl.Controls.Add(Ctrl.MakeLabel("", true), 0, 13);
            tl.Controls.Add(btnFolder, 1, 12);

            Button btnSave = Ctrl.AccentButton("Save Settings");
            btnSave.Dock   = DockStyle.Fill;
            btnSave.Margin = new Padding(18, 2, 0, 6);
            btnSave.Click += delegate(object s, EventArgs e) { SaveSettings(); };
            tl.Controls.Add(Ctrl.MakeLabel("", true), 0, 12);
            tl.Controls.Add(btnSave, 1, 13);

            _tabSettings.Controls.Add(tl);
        }

        void AddSettingRow(TableLayoutPanel tl, string label, Control ctl, int row)
        {
            tl.Controls.Add(Ctrl.MakeLabel(label, true), 0, row);
            // Anchor (stretches width, keeps ctl's own explicit Height),
            // not Dock.Fill (stretches both dimensions to the row's full
            // AutoSize height) - the Upload destination row's label wraps
            // to two lines, making that row's AutoSize height taller than
            // the single-line Download destination row above it; with
            // Dock.Fill each row's "..." browse button silently inherited
            // its own row's full height, so the two ended up visibly
            // different sizes (confirmed live: Height=26 vs Height=32 for
            // otherwise-identical buttons) even though both explicitly set
            // Height=26 on their own row Panel.
            ctl.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            ctl.Margin = new Padding(18, 4, 0, 4);
            tl.Controls.Add(ctl, 1, row);
        }

        // ── Theme apply ───────────────────────────────────────────────────────
        void ApplyTheme()
        {
            BackColor = Theme.Bg;
            // TabControl paints its own background (the strip of space
            // around/below the tab headers, outside any individual TabPage)
            // separately from every TabPage's own BackColor - left at its
            // ambient default this shows up as a thin light-gray gap right
            // under the tab headers even with owner-draw tabs.
            _tabs.BackColor = Theme.Bg;
            foreach (TabPage tp in _tabs.TabPages) tp.BackColor = Theme.Bg;
            if (_tabRowFill != null) _tabRowFill.BackColor = Theme.Bg;
            if (_tabFrameTop != null) _tabFrameTop.BackColor = Theme.Bg;
            if (_tabFrameBottom != null) _tabFrameBottom.BackColor = Theme.Bg;
            if (_tabFrameLeft != null) _tabFrameLeft.BackColor = Theme.Bg;
            if (_tabFrameRight != null) _tabFrameRight.BackColor = Theme.Bg;
            if (_tabGroupTop != null) _tabGroupTop.BackColor = Theme.Bg;
            if (_tabInterGapFill != null) _tabInterGapFill.BackColor = Theme.Bg;
            // Only needed in dark mode - _cmbArch's FlatStyle.Standard in
            // light mode renders a normal native border with no defect to
            // cover (see _cmbArch's own construction comment).
            if (_archBorderLeft != null)
            {
                _archBorderLeft.Visible = _archBorderTop.Visible =
                    _archBorderBottom.Visible = _archButtonFace.Visible = Theme.IsDark;
                _archBorderLeft.BackColor = _archBorderTop.BackColor =
                    _archBorderBottom.BackColor = Theme.Border;
                _archButtonFace.BackColor = Theme.EntryBg;
                _archButtonFace.Invalidate();
            }
            // Accessing .Handle forces the native window to exist now, so
            // this is safe to call before the form is ever shown (same
            // "force creation" pattern as EnableDarkScrollBar elsewhere).
            NativeMethods.SetDarkTitleBar(Handle, Theme.IsDark);
            // Immersive dark mode alone only covers the caption background/
            // text/buttons - Windows 11 draws a separate thin border around
            // the whole window that stays the system default color unless
            // set explicitly (see SetBorderAndCaptionColor's own comment).
            NativeMethods.SetBorderAndCaptionColor(Handle,
                Theme.IsDark ? Theme.Border  : Color.Empty,
                Theme.IsDark ? Theme.Surface : Color.Empty);
            if (_logBox != null)
            {
                _logBox.BackColor = Theme.LogBg;
                _logBox.ForeColor = Theme.LogFg;
                RecolorLog(_logBox);
            }
            // Repaint every TextBox and ComboBox so they pick up the new theme.
            // Borderless controls only — we re-apply MakeEntry's rules here.
            RestyleEntries(this);
            Invalidate(true);
        }

        // Recursively walk every control and re-apply theme colours.
        void RestyleEntries(Control parent)
        {
            foreach (Control c in parent.Controls)
            {
                TextBox tb = c as TextBox;
                if (tb != null)
                {
                    if (Theme.IsDark)
                    {
                        tb.BackColor = Theme.EntryBg;
                        tb.ForeColor = Theme.EntryFg;
                    }
                    else
                    {
                        tb.BackColor = SystemColors.Window;
                        tb.ForeColor = SystemColors.WindowText;
                    }
                    // BorderStyle.FixedSingle can't be recolored - every
                    // MakeEntry() TextBox is wrapped in a Ctrl.Bordered()
                    // panel that owns BorderStyle instead (see its comment).
                    Panel wrapper = tb.Parent as Panel;
                    if (wrapper != null && wrapper.Controls.Count == 1 && wrapper.Controls[0] == tb)
                        Ctrl.RestyleBordered(wrapper);
                    else
                        tb.BorderStyle = Theme.IsDark ? BorderStyle.FixedSingle : BorderStyle.Fixed3D;
                }
                ComboBox cb = c as ComboBox;
                if (cb != null && !(c is RichTextBox))
                {
                    cb.FlatStyle = Theme.IsDark ? FlatStyle.Flat : FlatStyle.Standard;
                    cb.BackColor = Theme.IsDark ? Theme.EntryBg : SystemColors.Window;
                    cb.ForeColor = Theme.IsDark ? Theme.EntryFg : SystemColors.WindowText;
                    // A ComboBox caches its background brush on the native
                    // handle; FlatStyle/BackColor changes only take visual
                    // effect after the handle is recreated. Force it via the
                    // protected RecreateHandle() method using reflection.
                    try
                    {
                        System.Reflection.MethodInfo mi = typeof(Control).GetMethod(
                            "RecreateHandle",
                            System.Reflection.BindingFlags.Instance |
                            System.Reflection.BindingFlags.NonPublic);
                        if (mi != null) mi.Invoke(cb, null);
                    }
                    catch { }
                    cb.Refresh();
                }
                CheckBox chk = c as CheckBox;
                if (chk != null)
                {
                    chk.ForeColor = Theme.Fg;
                    chk.BackColor = Color.Transparent;
                }
                RadioButton rb = c as RadioButton;
                if (rb != null)
                    rb.ForeColor = Theme.Fg;
                Label lbl = c as Label;
                if (lbl != null && !(c is RichTextBox) &&
                    lbl.ForeColor != Theme.Accent && lbl.ForeColor != Theme.Ok &&
                    lbl.ForeColor != Theme.Err  && lbl.ForeColor != Theme.Warn)
                    lbl.ForeColor = Theme.FgDim;
                if (c.HasChildren) RestyleEntries(c);
            }
        }

        void RecolorLog(RichTextBox box)
        {
            if (box == null || box.IsDisposed || box.TextLength == 0) return;
            int savedStart  = box.SelectionStart;
            int savedLength = box.SelectionLength;
            box.SuspendLayout();
            string[] logLines = box.Text.Split('\n');
            int pos = 0;
            foreach (string line in logLines)
            {
                if (line.Length == 0) { pos++; continue; }
                int tsEnd    = line.IndexOf("] ");
                int msgStart = tsEnd >= 0 ? tsEnd + 2 : 0;
                if (tsEnd >= 0) { box.Select(pos, tsEnd + 2); box.SelectionColor = Theme.FgDim; }
                string msgBody = tsEnd >= 0 ? line.Substring(tsEnd + 2) : line;
                box.Select(pos + msgStart, line.Length - msgStart);
                box.SelectionColor = MsgColor(msgBody);
                pos += line.Length + 1;
            }
            box.Select(savedStart, savedLength);
            box.ResumeLayout();
        }

        Color MsgColor(string msg)
        {
            string low = msg.ToLower();
            if (low.Contains("error")   || low.Contains("fail")    ||
                low.Contains("mismatch")|| low.Contains("abort"))    return Theme.Err;
            if (low.Contains("verified")|| low.Contains("complete")||
                low.Contains("success") || low.Contains("done"))     return Theme.Ok;
            if (low.Contains("skipping")|| low.Contains("already") ||
                low.Contains("sleeping")|| low.Contains("warning") ||
                low.Contains("waiting") || msg.StartsWith("WARN"))   return Theme.Warn;
            if (msg.StartsWith("===")   || msg.StartsWith("---"))    return Theme.Accent;
            return Theme.LogFg;
        }

        // ── Log helpers ───────────────────────────────────────────────────────
        void QueueLog(string msg)
        {
            lock (_logLock) _logQueue.Enqueue(msg);
        }

        DateTime _lastLogClear = DateTime.UtcNow;

        // Called by the 100 ms timer on the UI thread.
        void OnUiTick()
        {
            // Auto-clear in-app log every hour to prevent memory growth.
            if ((DateTime.UtcNow - _lastLogClear).TotalHours >= 1.0)
            {
                if (_logBox != null && !_logBox.IsDisposed) _logBox.Clear();
                _lastLogClear = DateTime.UtcNow;
                QueueLog("Log cleared (auto, hourly).");
            }

            // ── Flush log queue in one batched RTB update ────────────────
            List<string> batch = null;
            lock (_logLock)
            {
                if (_logQueue.Count > 0)
                {
                    batch = new List<string>(_logQueue);
                    _logQueue.Clear();
                }
            }
            if (batch != null && _logBox != null && !_logBox.IsDisposed)
            {
                _logBox.SuspendLayout();
                foreach (string msg in batch)
                    AppendLogToBox(msg, _logBox);
                _logBox.ResumeLayout();
                _logBox.ScrollToCaret();
            }

            // ── Refresh progress bar + label ─────────────────────────────
            if (_busy)
            {
                long done  = System.Threading.Interlocked.Read(ref _progDone);
                long total = System.Threading.Interlocked.Read(ref _progTotal);
                double spd;
                lock (_logLock) spd = _progSpeed;
                if (total > 0 || done > 0)
                {
                    _dlBar.Value = _progPct;
                    _lblProgress.Text = total > 0
                        ? string.Format("{0:F1} / {1:F1} MB  -  {2:F1} MB/s",
                            done / 1048576.0, total / 1048576.0, spd)
                        : string.Format("{0:F1} MB  -  {2:F1} MB/s",
                            done / 1048576.0, spd);
                }
            }
        }

        void AppendLog(string msg)
        {
            AppendLogToBox(msg, _logBox);
        }

        void AppendLogToBox(string msg, RichTextBox box)
        {
            if (box == null || box.IsDisposed) return;
            string ts  = "[" + DateTime.Now.ToString("HH:mm:ss") + "] ";
            Color  col = MsgColor(msg);

            box.SelectionStart  = box.TextLength;
            box.SelectionLength = 0;
            box.SelectionColor  = Theme.FgDim;
            box.AppendText(ts);
            box.SelectionStart  = box.TextLength;
            box.SelectionColor  = col;
            box.AppendText(msg + "\n");
            // ScrollToCaret called once per batch by OnUiTick, not per message.
        }

        void ClearLog()
        {
            if (_logBox != null && !_logBox.IsDisposed) _logBox.Clear();
        }

        void ClearLogFile()
        {
            if (ThemedMessageBox.Show(
                    "Permanently erase:\n" + Logger.LogFilePath + "\n\nCannot be undone.",
                    "Clear log file", MessageBoxButtons.YesNo, MessageBoxIcon.Warning)
                != DialogResult.Yes) return;
            try
            {
                Logger.ClearFile(); ClearLog();
                Logger.Log("Log file cleared.");
            }
            catch (Exception ex)
            {
                ThemedMessageBox.Show("Could not clear log file:\n" + ex.Message,
                    "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        // ── Status / busy ─────────────────────────────────────────────────────
        void SetStatus(string msg)
        {
            if (InvokeRequired) { BeginInvoke(new Action<string>(SetStatus), msg); return; }
        }

        void SetBusy(bool busy)
        {
            if (InvokeRequired) { BeginInvoke(new Action<bool>(SetBusy), busy); return; }
            _busy             = busy;
            _spinBar.Visible  = busy;
            _btnStart.Enabled = !busy;
            _btnStop.Enabled  = busy;
            if (!busy)
            {
                System.Threading.Interlocked.Exchange(ref _progDone,  0);
                System.Threading.Interlocked.Exchange(ref _progTotal, 0);
                lock (_logLock) _progSpeed = 0;
                _progPct          = 0;
                _dlBar.Value      = 0;
                _lblProgress.Text = "Idle";
            }
        }

        // Called from worker thread — only stores values; UI timer applies them.
        void UpdateProgress(long done, long total, double speed)
        {
            System.Threading.Interlocked.Exchange(ref _progDone,  done);
            System.Threading.Interlocked.Exchange(ref _progTotal, total);
            lock (_logLock) _progSpeed = speed;
            _progPct = total > 0 ? (int)Math.Min(done * 100 / total, 100) : 0;
        }

        // ── Actions ───────────────────────────────────────────────────────────
        void OnStart()
        {
            if (_busy) return;
            _stopEvent.Reset();

            // Auto-save settings
            SaveSettings();

            string targetBuild = _tbBuild.Text.Trim();
            string targetArch  = null;   // null = all architectures
            if (!string.IsNullOrEmpty(targetBuild) && _cmbArch.SelectedIndex == 1)
                targetArch = "amd64";
            else if (!string.IsNullOrEmpty(targetBuild) && _cmbArch.SelectedIndex == 2)
                targetArch = "arm64";
            bool   runProc     = _cbRunProcessor.Checked;
            bool   useMonitor  = _cbMonitor.Checked;
            // Skip upload: checkbox state (not saved to config — session only)
            bool   skipUpload  = _cbSkipUpload != null && _cbSkipUpload.Checked;
            string uploadDest  = skipUpload ? "" : AppConfig.UploadDest;
            // Build the set of enabled branches from config (ignored for manual builds)
            HashSet<string> enabledBranches = new HashSet<string>(StringComparer.Ordinal);
            if (AppConfig.Branch26H2) enabledBranches.Add("Windows 11 26H2");
            if (AppConfig.Branch26H1) enabledBranches.Add("Windows 11 26H1");
            if (AppConfig.Branch23H2) enabledBranches.Add("Windows 11 23H2");
            bool   cleanup     = AppConfig.CleanupAfterUpload;

            if (runProc && string.IsNullOrEmpty(uploadDest) && !skipUpload)
            {
                if (ThemedMessageBox.Show(
                        "Processor is enabled but no upload destination is set.\n" +
                        "Files will be processed but NOT transferred.\n\nContinue anyway?",
                        "No upload destination",
                        MessageBoxButtons.YesNo, MessageBoxIcon.Question) != DialogResult.Yes)
                    return;
            }

            SetBusy(true);

            _worker = new Thread(delegate()
            {
                try
                {
                    if (useMonitor)
                    {
                        Logger.Log("Monitor mode – scanning every 5 minutes. Press Stop to exit.");
                        while (!_stopEvent.WaitOne(0))
                        {
                            Logger.LogUiOnly(Logger.Log, "Starting scan...");
                            Fetcher.Run(
                                string.IsNullOrEmpty(targetBuild) ? null : targetBuild,
                                targetArch,
                                enabledBranches,
                                runProc, uploadDest, cleanup,
                                Logger.Log, UpdateProgress, _stopEvent);
                            if (_stopEvent.WaitOne(0)) break;
                            Logger.LogUiOnly(Logger.Log, "Sleeping 5 minutes...");
                            for (int i = 0; i < 300; i++)
                            {
                                if (_stopEvent.WaitOne(1000)) break;
                            }
                        }
                    }
                    else
                    {
                        Fetcher.Run(
                            string.IsNullOrEmpty(targetBuild) ? null : targetBuild,
                            targetArch,
                            enabledBranches,
                            runProc, uploadDest, cleanup,
                            Logger.Log, UpdateProgress, _stopEvent);
                    }
                }
                catch (Exception ex)
                {
                    Logger.Log("Error: " + ex.Message);
                }
                finally
                {
                    SetBusy(false);
                }
            });
            _worker.IsBackground = true;
            _worker.Start();
        }

        void OnStop()
        {
            // Cooperative only - there's no child process to kill anymore
            // (WimLibApi/CabinetApi are both in-process DLL calls); their
            // progress callbacks poll this event and abort on their own.
            _stopEvent.Set();
            Logger.Log("Stop requested – waiting for the current operation to abort...");
        }

        void SaveSettings()
        {
            AppConfig.UploadDest         = _tbUploadDest  != null ? _tbUploadDest.Text.Trim()  : "";
            AppConfig.CleanupAfterUpload = _cbCleanup      != null && _cbCleanup.Checked;
            AppConfig.SkipUpload         = _cbSkipUpload   != null && _cbSkipUpload.Checked;
            AppConfig.MonitorMode        = _cbMonitor      != null && _cbMonitor.Checked;
            AppConfig.RunProcessor       = _cbRunProcessor != null && _cbRunProcessor.Checked;
            AppConfig.Branch26H2         = _cb26H2         != null && _cb26H2.Checked;
            AppConfig.Branch26H1         = _cb26H1         != null && _cb26H1.Checked;
            AppConfig.Branch23H2         = _cb23H2         != null && _cb23H2.Checked;
            if (_tbUserAgent != null && _tbUserAgent.Text.Trim().Length > 0)
                AppConfig.UserAgent = _tbUserAgent.Text.Trim();
            // Apply download directory change immediately
            if (_tbDownloadDir != null)
            {
                string dd = _tbDownloadDir.Text.Trim();
                AppConfig.DownloadDir = dd;
                Paths.SetDownloadDir(dd);
            }
            AppConfig.Save();
            Logger.Log("Settings saved. Download dir: " + Paths.DownloadDir);
        }

        // Owner-draws one tab header for _tabs (see its own comment for why
        // this replaces the native tab strip instead of just recoloring it).
        void DrawTab(object sender, DrawItemEventArgs e)
        {
            TabControl tc = (TabControl)sender;
            TabPage page = tc.TabPages[e.Index];
            bool selected = e.Index == tc.SelectedIndex;

            // GetTabRect(e.Index), not e.Bounds - a live same-process check
            // (reflection-queried GetTabRect + a debug log of e.Bounds from
            // inside this very method) showed e.Bounds is only inset ~2px
            // from GetTabRect (e.g. GetTabRect={X=2,Y=0,W=90,H=31} vs
            // e.Bounds={X=4,Y=2,W=86,H=27} for the same tab) - the normal,
            // documented owner-draw content margin, not a real bug. Using
            // GetTabRect here is harmless/slightly more complete but was NOT
            // what fixed the "tab text alignment looks off" complaint.
            //
            // The actual cause (found via a pixel grid-dump of a live
            // screenshot cross-referenced against GetTabRect+ClientToScreen):
            // _tabFrameLeft's overlay panel (below) used a hardcoded 14px
            // width measured against the OLD, narrower tab geometry from
            // earlier in this session - once _tabs.Padding was restored to
            // its intended Point(18,7) (widening each tab to 90px), that same
            // 14px cover was eating a real ~12px chunk out of the FIRST tab's
            // own left edge, painting it Theme.Bg over what should have been
            // its selected Theme.Surface fill. The tab's text itself sat
            // safely past that point (Padding.X=18 insets it well clear) so
            // it looked correctly centered on its own - it was the visibly
            // truncated fill block next to it that read as "misaligned".
            // Fixed by shrinking _tabFrameLeft/_tabFrameRight to 4px, which
            // still covers the real native artifact they exist for (verified:
            // no light sliver reappeared) without reaching into real tab fill.
            Rectangle bounds = tc.GetTabRect(e.Index);

            using (SolidBrush bg = new SolidBrush(selected ? Theme.Surface : Theme.Bg))
                e.Graphics.FillRectangle(bg, bounds);
            if (selected)
                using (Pen p = new Pen(Theme.Accent, 2))
                    e.Graphics.DrawLine(p, bounds.Left, bounds.Bottom - 1, bounds.Right, bounds.Bottom - 1);

            using (StringFormat sf = new StringFormat())
            {
                sf.Alignment = StringAlignment.Center;
                sf.LineAlignment = StringAlignment.Center;
                using (SolidBrush fg = new SolidBrush(selected ? Theme.Fg : Theme.FgDim))
                    e.Graphics.DrawString(page.Text.Trim(), tc.Font, fg, bounds, sf);
            }
        }

        // Owner-draws one item of _cmbArch, both the closed display box
        // (e.Index == -1 there is possible before any selection, hence the
        // guard) and each row of the open dropdown list - see the comment at
        // _cmbArch's construction for why this is needed at all.
        void DrawComboItem(object sender, DrawItemEventArgs e)
        {
            ComboBox cb = (ComboBox)sender;
            e.DrawBackground();
            if (e.Index < 0) return;

            bool selected = (e.State & DrawItemState.Selected) == DrawItemState.Selected;
            Color bg = selected
                ? (Theme.IsDark ? Theme.SelBg : SystemColors.Highlight)
                : (Theme.IsDark ? Theme.EntryBg : SystemColors.Window);
            Color fg = selected
                ? (Theme.IsDark ? Theme.EntryFg : SystemColors.HighlightText)
                : (Theme.IsDark ? Theme.EntryFg : SystemColors.WindowText);

            using (SolidBrush b = new SolidBrush(bg))
                e.Graphics.FillRectangle(b, e.Bounds);
            TextRenderer.DrawText(e.Graphics, cb.Items[e.Index].ToString(), cb.Font, e.Bounds,
                fg, TextFormatFlags.Left | TextFormatFlags.VerticalCenter);
            e.DrawFocusRectangle();
        }

        // One cell of the per-build file grid in ShowState. A read-only
        // TextBox rather than a Label - looks the same (no border, matching
        // background) but lets the user select and copy a name/checksum,
        // which a Label can never support.
        static TextBox MakeGridCell(string text, bool header)
        {
            TextBox c = new TextBox();
            c.Text        = text;
            c.ReadOnly    = true;
            c.TabStop     = false;
            c.BorderStyle = BorderStyle.None;
            c.Dock        = DockStyle.Fill;
            c.Margin      = new Padding(6, 3, 6, 0);
            c.Font        = header ? Ctrl.SegoUI(8.25f, FontStyle.Bold) : new Font("Consolas", 8f);
            c.ForeColor   = header ? Theme.FgDim : Theme.Fg;
            c.BackColor   = header ? Theme.Bg : Theme.Surface;
            return c;
        }

        // One row per (buildNum, arch) entry in builds.json. Built as plain
        // themed Panels/Labels/Buttons rather than a DataGridView - matches
        // this project's existing "no native control looks right in dark
        // mode" approach (FlatProgressBar/ThemedMessageBox for the same
        // reason - see Theme's header comment in Theme.cs).
        void ShowState()
        {
            Dictionary<string, Dictionary<string, BuildRecord>> builds = BuildState.Load();
            if (builds.Count == 0)
            {
                ThemedMessageBox.Show("No state file found yet.", "State",
                    MessageBoxButtons.OK, MessageBoxIcon.Information);
                return;
            }

            Form win = new Form();
            win.Text          = "Downloaded Builds";
            win.Size          = new Size(1100, 680);
            win.MinimumSize   = new Size(800, 420);
            win.BackColor     = Theme.Bg;
            win.Font          = Ctrl.SegoUI();
            win.StartPosition = FormStartPosition.CenterParent;

            List<string> buildNums = new List<string>(builds.Keys);
            buildNums.Sort(StringComparer.Ordinal);
            int archCount = 0;
            foreach (string bn in buildNums) archCount += builds[bn].Count;

            Label lbl = Ctrl.MakeLabel(archCount + " recorded build/arch entries", false, 11f);
            lbl.Dock = DockStyle.Top; lbl.Height = 32; lbl.Padding = new Padding(14, 6, 0, 0);

            FlowLayoutPanel list = new FlowLayoutPanel();
            list.Dock          = DockStyle.Fill;
            list.FlowDirection = FlowDirection.TopDown;
            list.WrapContents  = false;
            list.AutoScroll    = true;
            list.BackColor     = Theme.Bg;
            list.Padding       = new Padding(12, 4, 12, 12);

            bool canUpload = !string.IsNullOrEmpty(AppConfig.UploadDest);

            foreach (string buildNum in buildNums)
            {
                List<string> arches = new List<string>(builds[buildNum].Keys);
                arches.Sort(StringComparer.Ordinal);
                foreach (string arch in arches)
                {
                    string bn = buildNum, ar = arch; // capture for closures below
                    BuildRecord rec = builds[bn][ar];

                    // Column widths verified against real text metrics (a
                    // standalone MeasureString harness): Consolas 8pt needs
                    // ~390px for a full 64-char sha256 and ~197px for a
                    // 32-char md5 - these leave real margin, not just enough.
                    const int colName = 280, colMd5 = 230, colSha = 460, rowH = 22;

                    Panel row = new Panel();
                    row.Width       = 1000;
                    row.BackColor   = Theme.Surface;
                    row.Margin      = new Padding(0, 0, 0, 8);
                    row.Padding     = new Padding(10);

                    Label header = Ctrl.MakeLabel(bn + "  (" + ar + ")", false, 10.5f);
                    header.Font     = new Font(header.Font, FontStyle.Bold);
                    header.Location = new Point(10, 8);
                    row.Controls.Add(header);

                    Label completed = Ctrl.MakeLabel("Completed: " + rec.completedUtc, true, 8.5f);
                    completed.Location = new Point(10, 30);
                    row.Controls.Add(completed);

                    int collapsedHeight;
                    int expandedHeight;
                    TableLayoutPanel fileTable = null;
                    Label toggle = null;

                    if (rec.files.Count == 0)
                    {
                        Label none = Ctrl.MakeLabel("(no processed files recorded)", true, 8.5f);
                        none.Location = new Point(10, 52);
                        row.Controls.Add(none);
                        collapsedHeight = 52 + 18 + 10;
                        expandedHeight  = collapsedHeight;
                    }
                    else
                    {
                        // Collapsed by default so a long list of builds
                        // doesn't take excessive vertical space - the file
                        // grid (with its checksums) is the least-often-needed
                        // detail, shown only on request.
                        toggle = new Label();
                        toggle.Text      = "▸ " + rec.files.Count + " file(s)";
                        toggle.AutoSize  = true;
                        toggle.Font      = Ctrl.SegoUI(8.5f);
                        toggle.ForeColor = Theme.Accent;
                        toggle.BackColor = Color.Transparent;
                        toggle.Cursor    = Cursors.Hand;
                        toggle.Location  = new Point(10, 52);
                        row.Controls.Add(toggle);

                        fileTable = new TableLayoutPanel();
                        fileTable.Location        = new Point(10, 76);
                        fileTable.Size            = new Size(colName + colMd5 + colSha, rowH * (rec.files.Count + 1));
                        fileTable.ColumnCount      = 3;
                        fileTable.RowCount         = rec.files.Count + 1;
                        fileTable.CellBorderStyle  = TableLayoutPanelCellBorderStyle.Single;
                        fileTable.BackColor        = Theme.Border;
                        fileTable.Visible          = false;
                        fileTable.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, colName));
                        fileTable.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, colMd5));
                        fileTable.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, colSha));
                        for (int ri = 0; ri < fileTable.RowCount; ri++)
                            fileTable.RowStyles.Add(new RowStyle(SizeType.Absolute, rowH));

                        fileTable.Controls.Add(MakeGridCell("Name",   true), 0, 0);
                        fileTable.Controls.Add(MakeGridCell("MD5",    true), 1, 0);
                        fileTable.Controls.Add(MakeGridCell("SHA256", true), 2, 0);

                        int fr = 1;
                        foreach (BuildFileRecord f in rec.files)
                        {
                            fileTable.Controls.Add(MakeGridCell(f.name,   false), 0, fr);
                            fileTable.Controls.Add(MakeGridCell(f.md5,    false), 1, fr);
                            fileTable.Controls.Add(MakeGridCell(f.sha256, false), 2, fr);
                            fr++;
                        }

                        row.Controls.Add(fileTable);
                        collapsedHeight = 76 + 10;
                        expandedHeight  = 76 + fileTable.Height + 10;

                        Panel rowRef = row;
                        Label toggleRef = toggle;
                        TableLayoutPanel fileTableRef = fileTable;
                        int collapsedRef = collapsedHeight, expandedRef = expandedHeight;
                        toggle.Click += delegate(object s, EventArgs e)
                        {
                            bool nowExpanded = !fileTableRef.Visible;
                            fileTableRef.Visible = nowExpanded;
                            toggleRef.Text = (nowExpanded ? "▾ " : "▸ ") + rec.files.Count + " file(s)";
                            rowRef.Height = nowExpanded ? expandedRef : collapsedRef;
                        };
                    }

                    Button btnRemove = Ctrl.DangerButton("Remove");
                    btnRemove.Size     = new Size(90, 28);
                    btnRemove.Location = new Point(row.Width - 210, 8);
                    btnRemove.Anchor   = AnchorStyles.Top | AnchorStyles.Right;
                    btnRemove.Click += delegate(object s, EventArgs e)
                    {
                        if (ThemedMessageBox.Show(
                                "Remove " + bn + " (" + ar + ") from the state file?\n" +
                                "This will NOT delete any downloaded or processed files - " +
                                "the next scan (manual or monitor mode) will treat it as " +
                                "incomplete and rebuild it.",
                                "Confirm", MessageBoxButtons.YesNo, MessageBoxIcon.Question)
                                != DialogResult.Yes)
                            return;
                        Dictionary<string, Dictionary<string, BuildRecord>> cur = BuildState.Load();
                        if (cur.ContainsKey(bn))
                        {
                            cur[bn].Remove(ar);
                            if (cur[bn].Count == 0) cur.Remove(bn);
                            BuildState.Save(cur);
                        }
                        Logger.Log("Removed " + bn + " (" + ar + ") from state - will rebuild on next scan.");
                        win.Close();
                        ShowState();
                    };
                    row.Controls.Add(btnRemove);

                    Button btnUpload = Ctrl.NormalButton(canUpload ? "Upload" : "Upload (no dest)");
                    btnUpload.Size     = new Size(110, 28);
                    btnUpload.Location = new Point(row.Width - 110, 8);
                    btnUpload.Anchor   = AnchorStyles.Top | AnchorStyles.Right;
                    btnUpload.Enabled  = canUpload;
                    string origUploadText = btnUpload.Text;
                    btnUpload.Click += delegate(object s, EventArgs e)
                    {
                        string dest = AppConfig.UploadDest;
                        string bdir = Path.Combine(Paths.DownloadDir, bn, ar);
                        btnUpload.Enabled = false;
                        btnUpload.Text    = "Uploading...";
                        Thread t = new Thread(delegate()
                        {
                            try
                            {
                                // Deliberately never cascades into cleanup here
                                // even if that setting is on - a targeted
                                // "upload this again" click shouldn't also
                                // silently delete the local build folder.
                                Processor.UploadBuild(bdir, dest, false, Logger.Log, null);
                                Logger.Log("Manual upload finished for " + bn + " (" + ar + ").");
                            }
                            catch (Exception ex)
                            {
                                Logger.Log("Manual upload failed for " + bn + " (" + ar + "): " + ex.Message);
                            }
                            finally
                            {
                                try
                                {
                                    if (win.IsHandleCreated && !win.IsDisposed)
                                        win.BeginInvoke(new Action(delegate()
                                        {
                                            if (!btnUpload.IsDisposed)
                                            {
                                                btnUpload.Enabled = canUpload;
                                                btnUpload.Text    = origUploadText;
                                            }
                                        }));
                                }
                                catch { }
                            }
                        });
                        t.IsBackground = true;
                        t.Start();
                    };
                    row.Controls.Add(btnUpload);

                    row.Height = collapsedHeight;
                    list.Controls.Add(row);
                }
            }

            win.Controls.Add(list);
            win.Controls.Add(lbl);
            // Accessing .Handle forces the native control to exist now, so
            // the dark-scrollbar theming call below is safe here (same
            // pattern as the main log panel's own EnableDarkScrollBar call).
            NativeMethods.EnableDarkScrollBar(list.Handle);
            if (Theme.IsDark)
            {
                NativeMethods.SetDarkTitleBar(win.Handle, true);
                NativeMethods.SetBorderAndCaptionColor(win.Handle, Theme.Border, Theme.Surface);
            }
            win.ShowDialog(this);
        }

        void ClearState()
        {
            if (!File.Exists(Paths.StateFile))
            {
                ThemedMessageBox.Show("No state file found.", "State",
                    MessageBoxButtons.OK, MessageBoxIcon.Information);
                return;
            }
            if (ThemedMessageBox.Show(
                    "Clear the downloaded-builds state file?\n" +
                    "This will NOT delete any downloaded files.",
                    "Confirm",
                    MessageBoxButtons.YesNo, MessageBoxIcon.Question) != DialogResult.Yes)
                return;
            BuildState.Save(new Dictionary<string, Dictionary<string, BuildRecord>>());
            Logger.Log("State file cleared.");
        }

        protected override void OnFormClosing(FormClosingEventArgs e)
        {
            _stopEvent.Set();
            _logTimer.Stop();
            base.OnFormClosing(e);
        }
    }
}
